#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

vpn_gw=$(grep -P -o -m 1 '(?<=^Address)(\s{0,})[^/]+' < "${CONFIG_DIR}/wireguard/${VPN_CONF}.conf"| sed -e 's~^[=\ ]*~~')
vpn_gw="${vpn_gw%.*}.1"

while true; do
    if ! natpmpc -g "${vpn_gw}" &> /dev/null; then
        echo "[WARNING] [$(date '+%Y-%m-%d %H:%M:%S')] ProtonVPN endpoint \"${vpn_gw%.*}.1\" does not support port forwarding!"
    else
        port=$(natpmpc -g "${vpn_gw}" -a 1 0 udp 60 | grep -P -o -m 1 '(?<=Mapped public port\s)\d+')
        if [[ -n "${port}" ]]; then
            natpmpc -g "${vpn_gw}" -a 1 0 tcp 60 &> /dev/null
            touch "${CONFIG_DIR}/forwarded_port"
            old_port=$(cat "${CONFIG_DIR}/forwarded_port")
            if [[ "${port}" != "${old_port}" ]]; then
                echo "${port}" > "${CONFIG_DIR}/forwarded_port"
                # shellcheck source=/dev/null
                source "${APP_DIR}/proton_update_app"
            fi
            echo "[INFO] [$(date '+%Y-%m-%d %H:%M:%S')] ProtonVPN forwarded port is \"${port}\"."
        else
            echo "[WARNING] [$(date '+%Y-%m-%d %H:%M:%S')] ProtonVPN port forwarding failed!"
        fi
    fi
    sleep 45
done
