#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
LIBTORRENT=${LIBTORRENT}
----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/config/qBittorrent.conf" ]]; then
    echo "Installing default \"qBittorrent.conf\"..."
    mkdir -p "${CONFIG_DIR}/config"
    cp "${APP_DIR}/qBittorrent.conf" "${CONFIG_DIR}/config/qBittorrent.conf"
    find "${CONFIG_DIR}/config" \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi
