#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/config/qBittorrent.conf" ]]; then
    echo "Installing default \"qBittorrent.conf\"..."
    mkdir -p "${CONFIG_DIR}/config"
    cp "${APP_DIR}/qBittorrent.conf" "${CONFIG_DIR}/config/qBittorrent.conf"
    chown hotio:hotio -R "${CONFIG_DIR}/config"
fi
