#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/app/config/qBittorrent.conf" ]]; then
    echo "Installing default \"qBittorrent.conf\"..."
    mkdir -p "${CONFIG_DIR}/app/config"
    cp /app/qBittorrent.conf "${CONFIG_DIR}/app/config/qBittorrent.conf"
    chown hotio:hotio -R "${CONFIG_DIR}/app/config"
fi
